apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellov2
spec:
  replicas: 3
  selector:
    matchLabels:
      role: hellov2
  template:
    metadata:
      labels:
        role: hellov2
    spec:
      containers:
      - name: hello
        image: gcr.io/google-samples/hello-app:2.0
        ports:
        - containerPort: 8080