---
apiVersion: v1
kind: Service
metadata:
  name: hellov2
  annotations:
    metallb.universe.tf/address-pool: demo-pods-pool
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    role: hellov2